services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: